# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/spotify.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/spotify.proto\"C\n\x12\x43lientTokenRequest\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x1d\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\r.InnerMessage\"`\n\x0cInnerMessage\x12\x13\n\x0b\x61pp_version\x18\x01 \x01(\t\x12\x19\n\x11hash_of_something\x18\x02 \x01(\t\x12 \n\x06\x66ield3\x18\x03 \x01(\x0b\x32\x10.NestedStructure\"I\n\x0fNestedStructure\x12&\n\x06\x66ield1\x18\x01 \x01(\x0b\x32\x16.AnotherestedStructure\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\t\"6\n\x15\x41notherestedStructure\x12\x1d\n\x06\x66ield1\x18\x01 \x01(\x0b\x32\r.SubStructure\"\xb0\x01\n\x0cSubStructure\x12 \n\x06\x66ield1\x18\x01 \x01(\x0b\x32\x10.SubSubStructure\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\t\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\t\x12\x0e\n\x06\x66ield6\x18\x06 \x01(\t\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\t\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\x05\x12\x0e\n\x06\x66ield9\x18\t \x01(\t\"a\n\x0fSubSubStructure\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.spotify_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTTOKENREQUEST._serialized_start=23
  _CLIENTTOKENREQUEST._serialized_end=90
  _INNERMESSAGE._serialized_start=92
  _INNERMESSAGE._serialized_end=188
  _NESTEDSTRUCTURE._serialized_start=190
  _NESTEDSTRUCTURE._serialized_end=263
  _ANOTHERESTEDSTRUCTURE._serialized_start=265
  _ANOTHERESTEDSTRUCTURE._serialized_end=319
  _SUBSTRUCTURE._serialized_start=322
  _SUBSTRUCTURE._serialized_end=498
  _SUBSUBSTRUCTURE._serialized_start=500
  _SUBSUBSTRUCTURE._serialized_end=597
# @@protoc_insertion_point(module_scope)
